apiVersion: v1
kind: Pod
metadata:
  name: django
  namespace: edu-dmitrij-gukalin
  labels:
    app: django
spec:
  containers:
    - name: django
      image: dzimag/django-app-k8s:latest
      ports:
        - containerPort: 8000
      envFrom:
        - secretRef:
            name: postgres-ssl-cert
        - secretRef:
            name: bucket
        - secretRef:
            name: django-secrets
        - configMapRef:
            name: django-config
      volumeMounts:
        - name: ssl-certs
          mountPath: /etc/ssl/certs
          readOnly: true
  volumes:
    - name: ssl-certs
      secret:
        secretName: postgres-ssl-cert
        items:
          - key: root.crt
            path: root.crt
  restartPolicy: Always
