apiVersion: v1
kind: Service
metadata:
  name: main-nginx
  namespace: edu-dmitrij-gukalin
spec:
  type: NodePort
  selector:
    app: main-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30896
